services:
  - type: web
    name: project-pa
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///project_pa.db
    dockerCommand: gunicorn --workers 2 --bind 0.0.0.0:$PORT app:app
